# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

boxes = [
    {
        :name => "centos7-bt-auto",
        :eth1 => "192.168.200.10",
        :mem => "1024",
        :cpu => "1"
    },
   # {
   #     :name => "docker-node2",
   #     :eth1 => "192.168.205.11",
   #     :mem => "1024",
   #     :cpu => "1"
   # }
 
]
 
Vagrant.configure("2") do |config|
 
 # vagrant box add centos7_bt  #的名称
  config.vm.box = "centos7_bt"

boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.provider "vmware_fusion" do |v|
          v.vmx["memsize"] = opts[:mem]
          v.vmx["numvcpus"] = opts[:cpu]
        end

        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        end

        config.vm.network :private_network, ip: opts[:eth1]
      end
  end
  
  
  #同步目录
  #config.vm.synced_folder "../work", "/home/mywork"
  config.vm.synced_folder "../work/php/masterfuture/", "/www/wwwroot/masterfuture/"
  # 端口转发
  config.vm.network "forwarded_port", guest: 80, host: 80 ,id:"nginx"
  #config.vm.network "forwarded_port", guest: 8888, host: 8889 ,id:"apache2"
  #执行特定脚本
   config.vm.provision "shell", privileged: true, path: "./setup.sh"
end
