<?php
 //微信资源文件管理
namespace app\assets;

use yii\web\AssetBundle;


class AdminAsset extends AssetBundle
{

    public function registerAssetFiles($view)
    {
        //版本号需要计算，或者有其他计算逻辑的时候得这样写
        $release_version = defined('RELEASE_VERSION')?RELEASE_VERSION:time();
        $this->css = [
            'css/admin/bootstrap.min.css',
            '/font-awesome/css/font-awesome.css',
            'css/admin/style.css?ver='.$release_version,
             
            'plugins/layui/css/layui2.4.2.css',  
        ];
        
        $this->js=[
           // 'http://res.wx.qq.com/open/js/jweixin-1.2.0.js',
            'js/jquery/jquery.min.js',
            'js/admin/bootstrap.js',
            'plugins/TouchSlide.1.1.js',
            'js/admin/common.js?ver='.$release_version,
            'plugins/layui/layui.js',
            
        ];
        
        
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }

}
