<?php
 //会员端的资源文件管理
namespace app\assets;

use yii\web\AssetBundle;


class FrontAsset extends AssetBundle
{

    public function registerAssetFiles($view)
    {
        //版本号需要计算，或者有其他计算逻辑的时候得这样写
        $release_version = defined('RELEASE_VERSION')?RELEASE_VERSION:time();
        $this->css = [
           
            'plugins/layui/css/layui2.4.2.css',  
             
            //自定义全局css
            'css/front/global.css?ver='.$release_version,         
           // 'css/front/css_style.css?ver='.$release_version,    
            
           
        ];

        $this->js=[
            'plugins/jquery.min.js',    
            'plugins/layui/layui.js',
            //自定义封装全局js代码
            'js/front/common.js?ver='.$release_version,             
        ];


        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }

}
